resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: operator
  newName: registry.redhat.io/openshift-builds/openshift-builds-rhel9-operator
  newTag: 1.4.0
